name: Update nix-direnv

"on":
  schedule:
    - cron: "0 0 16 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-nix-direnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Update nix-direnv to the latest version
        run: nix run '.#update-nix-direnv'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          assignees: ${{ github.repository_owner }}
          branch: "update/nix-direnv"
          commit-message: "chore(deps): Update nix-direnv"
          title: "chore(deps): Update nix-direnv"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
